---
title: "STA6856 Time Series"
subtitle: "Assignment 3"
author: "Hector Gavilanes"
format: html
embed-resources: true
execute: 
  warning: false
  message: false
editor: visual
---

We are going to fit an SARIMA(p, d, q) × (P, D, Q)s model to a dataset. We will be using the Monthly Live birth in thousands in the U.S., 1948 to 1979.

This data is given by birth in package `astsa`. You can proceed as follows:

```{r}
library(itsmr)
library(astsa)
library(forecast)
library(fpp3)
```

1.  Examine the plots of the time series, its ACF, and its PACF.

2.  Do a transformation and eliminate the trend and/or seasonal components, if applicable.

3.  Test IID hypothesis for the residuals R1.

4.  If the IID hypothesis is rejected then test the stationary hypothesis.

5.  If the stationary hypothesis is not rejected then based on ACF and PACF of the residuals list the potential models.

6.  Fit and compare the models using AIC Present the result in a table as follows (give at least 5 models), including the auto.arima model.

    | Models | p   | d   | q   | P   | D   | Q   | $\sigma^2$ | AIC | IDD hypothesis |
    |--------|-----|-----|-----|-----|-----|-----|------------|-----|----------------|
    | 1      |     |     |     |     |     |     |            |     |                |
    | ...    |     |     |     |     |     |     |            |     |                |

7.  Diagnostic check of the residuals from the SARIMA models being fitted.

8.  Select a final SARIMA model and type its equation.

9.  Split data to two data sets: training (367 obs.) and testing (the most recent/last 6 obs.)

10. Fit a SARIMA model to the training series and forecast the next 6 observations.

11. Run ARAR and Holt-Winters algorithms to predict the same number of observations.

12. Compare the models in terms of MAPE.
